apiVersion: v1
kind: Namespace
metadata:
  name: python-demo-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-demo-api
  namespace: python-demo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-demo-api
  template:
    metadata:
      labels:
        app: python-demo-api
    spec:
      containers:
      - name: python-demo-api
        image: ghcr.io/david-gimelle/azure-devops-pipeline-python/python-demo-api:placeholder
        ports:
        - containerPort: 5001
        env:
        - name: POETRY_VERSION
          value: "1.1.11"
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: python-demo-api-service
  namespace: python-demo-api
spec:
  type: LoadBalancer
  selector:
    app: python-demo-api
  ports:
    - protocol: TCP
      port: 8282
      targetPort: 5001